package com.varunmatangi.order_service.mapper;

import com.varunmatangi.order_service.dto.CreateOrderRequestDTO;
import com.varunmatangi.order_service.dto.OrderItemRequest;
import com.varunmatangi.order_service.dto.OrderItemResponse;
import com.varunmatangi.order_service.dto.OrderResponseDTO;
import com.varunmatangi.order_service.entity.Order;
import com.varunmatangi.order_service.entity.OrderItem;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;

import java.util.List;

@Mapper(componentModel = "spring")
public interface OrderMapper {
    // Request → Entity
    @Mapping(target = "orderId", ignore = true) // generated by DB
    @Mapping(target = "orderItems", ignore = true) // handled manually
    @Mapping(target = "totalAmount", ignore = true)
    Order toEntity(CreateOrderRequestDTO request);

    @Mapping(target = "orderItemId", ignore = true)
    @Mapping(target = "order", ignore = true) // set manually
    @Mapping(target = "subtotal", expression = "java(itemRequest.getPrice() * itemRequest.getQuantity())")
    OrderItem toEntity(OrderItemRequest itemRequest);

    // Entity → Response
    OrderResponseDTO toResponse(Order order);

    List<OrderResponseDTO> toResponseList(List<Order> orders);

    OrderItemResponse toResponse(OrderItem item);
}
